title: Deepika Gonela
logo: assets/img/FullSizeRender.jpeg
description: Welcome to my portfolio!
plugins:
- jekyll-theme-minimal # add this line to the plugins list if you already have one



navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: Experience
    url: /experience
