title: Hema Varshita Muppalla
logo: IMG_3463.heic
theme: jekyll-theme-minimal

navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: Experience
    url: /experience
