title: Hema Varshita Muppalla
logo: /assets/img/IMG_3463.heic
theme: jekyll-theme-minimal

navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Projects
    url: /projects
  - title: Experience
    url: /experience
  - title: Contact
    url: /contact
