title: Deepika Gonela
logo: assets/img/FullSizeRender.jpeg
description: Welcome to my portfolio!
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-theme-minimal # add this line to the plugins list if you already have one
include: ["assets/custom.css"]

navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: Experience
    url: /experience
