title: Hema Varshita Muppalla
logo: assets/img/IMG_3463.jpg
theme: jekyll-theme-minimal

navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: Experience
    url: /experience
